variables: 
- group: 'github-pat-mon-github'
- name: 'github-organisation'
  value: 'it-consultingco'
- name: 'github-repository'
  value: 'testing'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'GitPush'
  jobs:
    - job: GitPush
      steps:
        - checkout: self
        - script: git push https://$(github-pat-mon-github)@github.com/$(github-organisation)/$(github-repository).git HEAD:refs/heads/master
          displayName: 'Git push to remote repository'
          env:
            github-pat-mon-github: $(github-pat-mon-github)