trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
  - checkout: self
  - script: git remote add origin https://$GHPAT@github.com/it-consultingco/Testing.git
    displayName: 'Add remote origin'
  - script: git push -u origin master
    displayName: 'Push to remote origin'