trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
  - script: git remote remove origin
    displayName: 'Cleanup remote origin'
  - script: git push https://$(GHPAT)@github.com/it-consultingco/Testing.git HEAD:refs/heads/master
    displayName: 'Add remote origin'
  - script: git push -u origin master
    displayName: 'Push to remote origin'
    env:
      MY_MAPPED_ENV_VAR: $(GHPAT)