trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'GitPush'
  jobs:
    - job: GitPush
      steps:
        - checkout: self
        - script: git push https://$(GITHUB-PAT-MON-GITHUB)@github.com/it-consultingco/Testing.git HEAD:refs/heads/master
          displayName: 'Git push to remote repository'
          env:
            GITHUB-PAT-MON-GITHUB: $(GITHUB-PAT-MON-GITHUB)