trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
  - checkout: self
  - script: git push https://$GHPAT@github.com/it-consultingco/Testing.git HEAD:master
    displayName: 'Push to remote repository'